# Generated by Django 4.2.8 on 2023-12-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
